# starship.toml
format = "$all"



add_newline = true
[character]
error_symbol = "[âœ](bold red)"
success_symbol = "[âœ](bold green)"

#success_symbol = "[>>](bold green)"
#error_symbol = "[>>](bold red)"
# success_symbol = "[[~](bold green)>](bold white)"


[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[cmd_duration]
disabled = true


[deno]
format = "via [ğŸ¦• $version](green bold) "

